[package]
name = "uav"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Accurate UAV simulation by integrating dynamics model "
keywords = ["uav", "quadcopter"]
repository = "https://github.com/stillonearth/bevy_urdf"

[dependencies]
fast_ode = "1.0"
nalgebra = "0.33"